name: Deploy to development

on:
  push:
    branches: ["main"]

jobs:
  development-workflow:
    uses: s0rl0v/weather-app/.github/workflows/cicd.yml@main
    with:
      environment: development
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
