name: Deploy to staging

on:
  push:
    branches: ["release/*"]

jobs:
  staging-workflow:
    uses: s0rl0v/weather-app/.github/workflows/cicd.yml@main
    with:
      environment: staging
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
